spring.application.name=StockSimulationGame2026

# DB ?? ??
spring.datasource.url=jdbc:mysql://localhost:3306/stock_SSG?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=qu1tfuck1n9h@ck

# JPA/Hibernate ??
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ?? ?? (?? 8080)
server.port=8080
